### ISSUE TITLE
update warns python-future package is not available

### ISSUE THREAD

**Issue by ki4rbc** [km4ack/pi-build#141] opened 2020-09-19 20:17 UTC
The first time I ran update, I get the following output during the scan:
```
Checking Rig Control
Checking FLDIGI
Checking FLWRAP
Checking FLRIG
Checking FLAMP
Checking FLMSG
Checking FLNET
Checking Pat Winlink
Checking Chirp
WARNING: python-future package is not available; chirp.drivers.anytone778uv requires it
WARNING: python-future package is not available; chirp.drivers.ga510 requires it
WARNING: python-future package is not available; chirp.drivers.tk8180 requires it
WARNING: python-future package is not available; chirp.drivers.tmd710 requires it
Checking Direwolf
Checking Pat Menu
Checking GARIM
```
I quit and installed the missing package:
```
$ sudo apt-get install python-future -y
```
Afterwards, the update did not issue this warning on scan.

I'm not sure if I missed a step or is this a new problem.

73s

KI4RBC

**Comment by km4ack** [comment] 2020-09-20 11:27
Duplicate of issue #109

**Closed by km4ack** 2020-09-20 11:27 UTC
Labels: duplicate
